packages:
  - apps/*
  - packages/*
catalog:
  "@commitlint/cli": ^20.1.0
  "@commitlint/config-conventional": ^20.0.0
  "@commitlint/prompt-cli": ^20.1.0
  "@hookform/resolvers": ^5.2.2
  "@nestjs/cli": ^11.0.0
  "@nestjs/common": ^11.0.1
  "@nestjs/core": ^11.0.1
  "@nestjs/platform-express": ^11.0.1
  "@nestjs/schematics": ^11.0.0
  "@nestjs/testing": ^11.0.1
  "@next/eslint-plugin-next": ^15.5.4
  "@radix-ui/react-accordion": ^1.2.12
  "@radix-ui/react-alert-dialog": ^1.1.15
  "@radix-ui/react-aspect-ratio": ^1.1.7
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-checkbox": ^1.3.3
  "@radix-ui/react-collapsible": ^1.1.12
  "@radix-ui/react-context-menu": ^2.2.16
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-dropdown-menu": ^2.1.16
  "@radix-ui/react-hover-card": ^1.1.15
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-menubar": ^1.1.16
  "@radix-ui/react-navigation-menu": ^1.2.14
  "@radix-ui/react-popover": ^1.1.15
  "@radix-ui/react-progress": ^1.1.7
  "@radix-ui/react-radio-group": ^1.3.8
  "@radix-ui/react-scroll-area": ^1.2.10
  "@radix-ui/react-select": ^2.2.6
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slider": ^1.3.6
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-switch": ^1.2.6
  "@radix-ui/react-tabs": ^1.1.13
  "@radix-ui/react-toggle": ^1.1.10
  "@radix-ui/react-toggle-group": ^1.1.11
  "@radix-ui/react-tooltip": ^1.2.8
  "@t3-oss/env-core": ^0.13.8
  "@tailwindcss/postcss": ^4.1.14
  "@tsconfig/next": ^2.0.3
  "@tsconfig/node-lts": ^22.0.2
  "@tsconfig/recommended": ^1.0.10
  "@turbo/gen": ^2.5.8
  "@types/express": ^5.0.0
  "@types/jest": ^30.0.0
  "@types/lodash": ^4.17.20
  "@types/pg": ^8.15.5
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.1
  "@types/supertest": ^6.0.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  country-data-list: ^1.5.5
  date-fns: ^4.1.0
  dotenv: ^17.2.2
  dotenv-cli: ^10.0.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.6
  drizzle-zod: ^0.8.3
  embla-carousel-react: ^8.6.0
  eslint-config-next: 15.5.4
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-turbo: ^2.5.8
  husky: ^9.1.7
  input-otp: ^1.4.2
  jest: ^30.0.0
  lint-staged: ^16.2.4
  lucide-react: ^0.545.0
  next: 15.5.4
  next-themes: ^0.4.6
  pg: ^8.16.3
  postgres: ^3.4.7
  react-circle-flags: ^0.0.23
  react-day-picker: ^9.11.1
  react-hook-form: ^7.65.0
  react-phone-number-input: ^3.4.12
  react-resizable-panels: ^3.0.6
  recharts: 3.2.1
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  sonner: ^2.0.7
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  tailwind-merge: ^3.3.1
  tailwind-scrollbar-hide: ^4.0.0
  tailwindcss: ^4.1.14
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsup: ^8.5.0
  turbo: ^2.5.8
  tw-animate-css: ^1.4.0
  uuid: ^13.0.0
  vaul: ^1.1.2
  zod: ^4.1.12
