import type { NativeFieldDefinition } from "./types";

/**
 * Native field definitions for Email Campaigns (org_email_campaigns)
 */
export const orgEmailCampaignsFields: NativeFieldDefinition[] = [
  {
    id: "name",
    label: "Campaign name",
    type: "text",
    category: "identity",
    group: "Campaign Info",
    sortOrder: 1,
  },
  {
    id: "status",
    label: "Status",
    type: "picklist",
    category: "metadata",
    group: "Campaign Status",
    sortOrder: 1,
  },
  {
    id: "subject",
    label: "Subject",
    type: "text",
    category: "metadata",
    group: "Content",
    sortOrder: 1,
  },
  {
    id: "targetTags",
    label: "Target tags",
    type: "tag",
    category: "classification",
    group: "Audience",
    sortOrder: 1,
    tag: {
      relatedType: "contact",
    },
  },
  {
    id: "tagMatchType",
    label: "Tag match type",
    type: "picklist",
    category: "classification",
    group: "Audience",
    sortOrder: 2,
  },
  {
    id: "targetCategories",
    label: "Target categories",
    type: "multipicklist",
    category: "classification",
    group: "Audience",
    sortOrder: 3,
  },
  {
    id: "scheduledFor",
    label: "Scheduled for",
    type: "datetime",
    category: "activity",
    group: "Scheduling",
    sortOrder: 1,
  },
  {
    id: "startedAt",
    label: "Started at",
    type: "datetime",
    category: "activity",
    group: "Scheduling",
    sortOrder: 2,
  },
  {
    id: "completedAt",
    label: "Completed at",
    type: "datetime",
    category: "activity",
    group: "Scheduling",
    sortOrder: 3,
  },
  {
    id: "cancelledAt",
    label: "Cancelled at",
    type: "datetime",
    category: "activity",
    group: "Scheduling",
    sortOrder: 4,
  },
  {
    id: "totalRecipients",
    label: "Total recipients",
    type: "number",
    category: "metadata",
    group: "Performance",
    sortOrder: 1,
  },
  {
    id: "sentCount",
    label: "Sent",
    type: "number",
    category: "metadata",
    group: "Performance",
    sortOrder: 2,
  },
  {
    id: "deliveredCount",
    label: "Delivered",
    type: "number",
    category: "metadata",
    group: "Performance",
    sortOrder: 3,
  },
  {
    id: "openedCount",
    label: "Opened",
    type: "number",
    category: "metadata",
    group: "Performance",
    sortOrder: 4,
  },
  {
    id: "clickedCount",
    label: "Clicked",
    type: "number",
    category: "metadata",
    group: "Performance",
    sortOrder: 5,
  },
  {
    id: "bouncedCount",
    label: "Bounced",
    type: "number",
    category: "metadata",
    group: "Performance",
    sortOrder: 6,
  },
  {
    id: "complainedCount",
    label: "Complained",
    type: "number",
    category: "metadata",
    group: "Performance",
    sortOrder: 7,
  },
];
