import type { NativeFieldDefinition } from "./types";

/**
 * Native field definitions for Contacts (org_contacts)
 * Extracted from contact-record-layout.ts
 */
export const orgContactsFields: NativeFieldDefinition[] = [
  // Identity Fields
  {
    id: "name",
    label: "Name",
    type: "text",
    category: "identity",
    group: "Profile",
    sortOrder: 1,
  },
  {
    id: "salutation",
    label: "Salutation",
    type: "text",
    category: "identity",
    group: "Profile",
    sortOrder: 2,
  },
  {
    id: "firstName",
    label: "First name",
    type: "text",
    category: "identity",
    group: "Profile",
    sortOrder: 3,
  },
  {
    id: "lastName",
    label: "Last name",
    type: "text",
    category: "identity",
    group: "Profile",
    sortOrder: 4,
  },
  {
    id: "avatarUrl",
    label: "Avatar",
    type: "text",
    category: "identity",
    group: "Profile",
    sortOrder: 5,
    isReadOnly: true,
  },

  // Contact Fields
  {
    id: "email",
    label: "Email",
    type: "text",
    category: "contact",
    group: "Contact",
    sortOrder: 1,
  },
  {
    id: "phone",
    label: "Phone",
    type: "phone",
    category: "contact",
    group: "Contact",
    sortOrder: 2,
  },
  {
    id: "websiteUrl",
    label: "Website",
    type: "text",
    category: "contact",
    group: "Contact",
    sortOrder: 3,
  },
  {
    id: "linkedinUrl",
    label: "LinkedIn",
    type: "text",
    category: "contact",
    group: "Contact",
    sortOrder: 4,
  },
  {
    id: "twitterHandle",
    label: "Twitter",
    type: "text",
    category: "contact",
    group: "Contact",
    sortOrder: 5,
  },

  // Organization Fields
  {
    id: "companyName",
    label: "Company",
    type: "text",
    category: "organization",
    group: "Organization",
    sortOrder: 1,
  },
  {
    id: "industry",
    label: "Industry",
    type: "text",
    category: "organization",
    group: "Organization",
    sortOrder: 2,
  },
  {
    id: "annualRevenueBand",
    label: "Revenue band",
    type: "text",
    category: "organization",
    group: "Organization",
    sortOrder: 3,
  },
  {
    id: "employeeCountBand",
    label: "Company size",
    type: "text",
    category: "organization",
    group: "Organization",
    sortOrder: 4,
  },

  // Classification Fields
  {
    id: "tags",
    label: "Tags",
    type: "tag",
    category: "classification",
    group: "Segmentation",
    sortOrder: 1,
    tag: {
      relatedType: "contact",
    },
  },
  {
    id: "categories",
    label: "Categories",
    type: "multipicklist",
    category: "classification",
    group: "Segmentation",
    sortOrder: 2,
    options: [
      { label: "item 1", value: "item 1" },
      { label: "item 2", value: "item 2" },
      { label: "item 3", value: "item 3" },
    ],
  },

  // Address Fields - Shipping
  {
    id: "shippingAddressLine1",
    label: "Address line 1",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 1,
  },
  {
    id: "shippingAddressLine2",
    label: "Address line 2",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 2,
  },
  {
    id: "shippingCity",
    label: "City",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 3,
  },
  {
    id: "shippingRegion",
    label: "State / region",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 4,
  },
  {
    id: "shippingPostalCode",
    label: "Postal code",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 5,
  },
  {
    id: "shippingCountryCode",
    label: "Country",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 6,
  },
  {
    id: "shippingLatitude",
    label: "Latitude",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 7,
  },
  {
    id: "shippingLongitude",
    label: "Longitude",
    type: "text",
    category: "address",
    group: "Shipping Address",
    sortOrder: 8,
  },

  // Address Fields - Billing
  {
    id: "billingAddressLine1",
    label: "Address line 1",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 11,
  },
  {
    id: "billingAddressLine2",
    label: "Address line 2",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 12,
  },
  {
    id: "billingCity",
    label: "City",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 13,
  },
  {
    id: "billingRegion",
    label: "State / region",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 14,
  },
  {
    id: "billingPostalCode",
    label: "Postal code",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 15,
  },
  {
    id: "billingCountryCode",
    label: "Country",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 16,
  },
  {
    id: "billingLatitude",
    label: "Latitude",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 17,
  },
  {
    id: "billingLongitude",
    label: "Longitude",
    type: "text",
    category: "address",
    group: "Billing Address",
    sortOrder: 18,
  },

  // Consent Fields
  {
    id: "emailOptIn",
    label: "Email opt-in",
    type: "boolean",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 1,
  },
  {
    id: "smsOptIn",
    label: "SMS opt-in",
    type: "boolean",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 2,
  },
  {
    id: "phoneOptIn",
    label: "Phone opt-in",
    type: "boolean",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 3,
  },
  {
    id: "doNotContact",
    label: "Do not contact",
    type: "boolean",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 4,
  },
  {
    id: "doNotSell",
    label: "Do not sell",
    type: "boolean",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 5,
  },
  {
    id: "emailConfirmedAt",
    label: "Email confirmed",
    type: "datetime",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 6,
    availableOnCreate: false,
    isReadOnly: true,
  },
  {
    id: "consentCapturedAt",
    label: "Consent captured",
    type: "datetime",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 7,
    availableOnCreate: false,
    isReadOnly: true,
  },
  {
    id: "consentSource",
    label: "Consent source",
    type: "text",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 8,
  },
  {
    id: "consentIp",
    label: "Consent IP",
    type: "text",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 9,
  },
  {
    id: "gdprConsentScope",
    label: "Consent scope",
    type: "text",
    category: "consent",
    group: "Consent & Preferences",
    sortOrder: 10,
  },

  // Activity Fields
  {
    id: "lastActivityAt",
    label: "Last activity",
    type: "datetime",
    category: "activity",
    group: "Activity",
    sortOrder: 1,
    isReadOnly: true,
  },
  {
    id: "nextActivityAt",
    label: "Next activity",
    type: "datetime",
    category: "activity",
    group: "Activity",
    sortOrder: 2,
  },

  // Metadata Fields
  {
    id: "languagePref",
    label: "Language preference",
    type: "text",
    category: "metadata",
    group: "Metadata",
    sortOrder: 1,
  },
  {
    id: "nationality",
    label: "Nationality",
    type: "text",
    category: "metadata",
    group: "Metadata",
    sortOrder: 2,
  },
  {
    id: "score",
    label: "Engagement score",
    type: "number",
    category: "metadata",
    group: "Metadata",
    sortOrder: 3,
  },
  {
    id: "birthday",
    label: "Birthday",
    type: "date",
    category: "metadata",
    group: "Metadata",
    sortOrder: 4,
  },
  {
    id: "notes",
    label: "Internal notes",
    type: "textarea",
    category: "metadata",
    group: "Notes",
    sortOrder: 5,
  },

  // System Fields
  {
    id: "dedupeKey",
    label: "Dedupe key",
    type: "text",
    category: "system",
    group: "System",
    sortOrder: 10,
  },
];
