import js from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";
import turboPlugin from "eslint-plugin-turbo";
import tseslint from "typescript-eslint";
import onlyWarn from "eslint-plugin-only-warn";
import perfectionist from "eslint-plugin-perfectionist";

/**
 * A shared ESLint configuration for the repository.
 *
 * @type {import("eslint").Linter.Config[]}
 * */
export const config = [
  js.configs.recommended,
  eslintConfigPrettier,
  ...tseslint.configs.recommended,
  {
    plugins: {
      turbo: turboPlugin,
    },
    rules: {
      "turbo/no-undeclared-env-vars": "warn",
    },
  },
  {
    plugins: {
      onlyWarn,
    },
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          args: "all",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    plugins: {
      perfectionist,
    },
    rules: {
      "perfectionist/sort-imports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          internalPattern: ["^~/.+", "^@/.+"],
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: 1,
          maxLineLength: undefined,
          groups: [
            "type-import",
            ["value-builtin", "value-external"],
            "type-internal",
            "value-internal",
            ["type-parent", "type-sibling", "type-index"],
            ["value-parent", "value-sibling", "value-index"],
            "ts-equals-import",
            "unknown",
          ],
          customGroups: [],
          environment: "node",
        },
      ],
      "perfectionist/sort-exports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          groupKind: "mixed",
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-array-includes": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "literals-first",
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-named-exports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreAlias: false,
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "mixed",
          partitionByNewLine: false,
          partitionByComment: false,
          newlinesBetween: "ignore",
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-named-imports": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreAlias: false,
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "mixed",
          partitionByNewLine: false,
          partitionByComment: false,
          newlinesBetween: "ignore",
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-sets": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          groupKind: "literals-first",
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groups: [],
          customGroups: [],
        },
      ],
      "perfectionist/sort-jsx-props": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          ignorePattern: [],
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          useConfigurationIf: {},
          groups: [],
          customGroups: {},
        },
      ],
      "perfectionist/sort-modules": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          groups: [
            "declare-enum",
            "export-enum",
            "enum",
            ["declare-interface", "declare-type"],
            ["export-interface", "export-type"],
            ["interface", "type"],
            "declare-class",
            "class",
            "export-class",
            "declare-function",
            "export-function",
            "function",
          ],
          customGroups: [],
        },
      ],
      "perfectionist/sort-classes": [
        "error",
        {
          type: "alphabetical",
          order: "asc",
          fallbackSort: { type: "unsorted" },
          ignoreCase: true,
          specialCharacters: "keep",
          partitionByComment: false,
          partitionByNewLine: false,
          newlinesBetween: "ignore",
          ignoreCallbackDependenciesPatterns: [],
          groups: [
            "index-signature",
            ["static-property", "static-accessor-property"],
            ["static-get-method", "static-set-method"],
            ["protected-static-property", "protected-static-accessor-property"],
            ["protected-static-get-method", "protected-static-set-method"],
            ["private-static-property", "private-static-accessor-property"],
            ["private-static-get-method", "private-static-set-method"],
            "static-block",
            ["property", "accessor-property"],
            ["get-method", "set-method"],
            ["protected-property", "protected-accessor-property"],
            ["protected-get-method", "protected-set-method"],
            ["private-property", "private-accessor-property"],
            ["private-get-method", "private-set-method"],
            "constructor",
            ["static-method", "static-function-property"],
            ["protected-static-method", "protected-static-function-property"],
            ["private-static-method", "private-static-function-property"],
            ["method", "function-property"],
            ["protected-method", "protected-function-property"],
            ["private-method", "private-function-property"],
            "unknown",
          ],
          customGroups: [],
        },
      ],
    },
  },
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
    ],
  },
];
