import type { CsvImportColumn } from '../csv-import.types';

export const ORG_OPPORTUNITIES_COLUMNS: CsvImportColumn[] = [
  {
    key: 'id',
    label: 'ID',
    type: 'string',
    description:
      'Provide an existing ID to update a record. Leave empty to create a new record.',
  },
  { key: 'name', label: 'Name', type: 'string' },
  { key: 'description', label: 'Description', type: 'string' },
  { key: 'ownerUserId', label: 'Owner User ID', type: 'string' },
  { key: 'teamId', label: 'Team ID', type: 'string' },
  { key: 'accountId', label: 'Account ID', type: 'string' },
  { key: 'primaryContactId', label: 'Primary Contact ID', type: 'string' },
  { key: 'type', label: 'Type', type: 'string' },
  { key: 'status', label: 'Status', type: 'string' },
  { key: 'probability', label: 'Probability', type: 'number' },
  { key: 'forecastCategory', label: 'Forecast Category', type: 'string' },
  { key: 'amount', label: 'Amount', type: 'number' },
  { key: 'currencyCode', label: 'Currency Code', type: 'string' },
  { key: 'exchangeRate', label: 'Exchange Rate', type: 'number' },
  { key: 'amountHome', label: 'Amount (Home)', type: 'number' },
  { key: 'expectedCloseDate', label: 'Expected Close Date', type: 'date' },
  { key: 'lastActivityAt', label: 'Last Activity At', type: 'date' },
  { key: 'nextActivityAt', label: 'Next Activity At', type: 'date' },
  { key: 'closedWonAt', label: 'Closed Won At', type: 'date' },
  { key: 'closedLostAt', label: 'Closed Lost At', type: 'date' },
  { key: 'nextStep', label: 'Next Step', type: 'string' },
  { key: 'source', label: 'Source', type: 'string' },
  { key: 'sourceDetail', label: 'Source Detail', type: 'string' },
  { key: 'utmSource', label: 'UTM Source', type: 'string' },
  { key: 'utmMedium', label: 'UTM Medium', type: 'string' },
  { key: 'utmCampaign', label: 'UTM Campaign', type: 'string' },
  { key: 'utmTerm', label: 'UTM Term', type: 'string' },
  { key: 'utmContent', label: 'UTM Content', type: 'string' },
  { key: 'lostReasonId', label: 'Lost Reason ID', type: 'string' },
  { key: 'lostReasonNote', label: 'Lost Reason Note', type: 'string' },
  { key: 'priority', label: 'Priority', type: 'string' },
  { key: 'tags', label: 'Tags', type: 'string[]' },
  { key: 'customFields', label: 'Custom Fields (JSON)', type: 'json' },
  { key: 'isArchived', label: 'Is Archived', type: 'boolean' },
];
