import type { CsvImportColumn } from '../csv-import.types';

export const ORG_CONTACTS_COLUMNS: CsvImportColumn[] = [
  {
    key: 'id',
    label: 'ID',
    type: 'string',
    description:
      'Provide an existing ID to update a record. Leave empty to create a new record.',
  },
  { key: 'firstName', label: 'First Name', type: 'string' },
  { key: 'lastName', label: 'Last Name', type: 'string' },
  { key: 'salutation', label: 'Salutation', type: 'string' },
  { key: 'name', label: 'Full Name', type: 'string' },
  { key: 'phone', label: 'Phone', type: 'string' },
  { key: 'phoneE164', label: 'Phone (E164)', type: 'string' },
  { key: 'email', label: 'Email', type: 'string' },
  { key: 'emailNormalized', label: 'Email (Normalized)', type: 'string' },
  { key: 'nationality', label: 'Nationality', type: 'string' },
  { key: 'tags', label: 'Tags', type: 'string[]' },
  { key: 'categories', label: 'Categories', type: 'string[]' },
  { key: 'notes', label: 'Notes', type: 'string' },
  { key: 'lastActivityAt', label: 'Last Activity At', type: 'date' },
  { key: 'nextActivityAt', label: 'Next Activity At', type: 'date' },
  { key: 'score', label: 'Score', type: 'number' },
  { key: 'emailOptIn', label: 'Email Opt-In', type: 'boolean' },
  { key: 'smsOptIn', label: 'SMS Opt-In', type: 'boolean' },
  { key: 'phoneOptIn', label: 'Phone Opt-In', type: 'boolean' },
  { key: 'emailConfirmedAt', label: 'Email Confirmed At', type: 'date' },
  { key: 'consentCapturedAt', label: 'Consent Captured At', type: 'date' },
  { key: 'consentSource', label: 'Consent Source', type: 'string' },
  { key: 'consentIp', label: 'Consent IP', type: 'string' },
  { key: 'gdprConsentScope', label: 'GDPR Consent Scope', type: 'string' },
  { key: 'doNotContact', label: 'Do Not Contact', type: 'boolean' },
  { key: 'doNotSell', label: 'Do Not Sell', type: 'boolean' },
  {
    key: 'shippingAddressLine1',
    label: 'Shipping Address Line 1',
    type: 'string',
  },
  {
    key: 'shippingAddressLine2',
    label: 'Shipping Address Line 2',
    type: 'string',
  },
  { key: 'shippingCity', label: 'Shipping City', type: 'string' },
  { key: 'shippingRegion', label: 'Shipping Region', type: 'string' },
  { key: 'shippingPostalCode', label: 'Shipping Postal Code', type: 'string' },
  {
    key: 'shippingCountryCode',
    label: 'Shipping Country Code',
    type: 'string',
  },
  { key: 'shippingLatitude', label: 'Shipping Latitude', type: 'number' },
  { key: 'shippingLongitude', label: 'Shipping Longitude', type: 'number' },
  {
    key: 'billingAddressLine1',
    label: 'Billing Address Line 1',
    type: 'string',
  },
  {
    key: 'billingAddressLine2',
    label: 'Billing Address Line 2',
    type: 'string',
  },
  { key: 'billingCity', label: 'Billing City', type: 'string' },
  { key: 'billingRegion', label: 'Billing Region', type: 'string' },
  { key: 'billingPostalCode', label: 'Billing Postal Code', type: 'string' },
  { key: 'billingCountryCode', label: 'Billing Country Code', type: 'string' },
  { key: 'billingLatitude', label: 'Billing Latitude', type: 'number' },
  { key: 'billingLongitude', label: 'Billing Longitude', type: 'number' },
  { key: 'languagePref', label: 'Language Preference', type: 'string' },
  { key: 'dedupeKey', label: 'Dedupe Key', type: 'string' },
  { key: 'externalIds', label: 'External IDs (JSON)', type: 'json' },
  { key: 'customFields', label: 'Custom Fields (JSON)', type: 'json' },
  { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'string' },
  { key: 'twitterHandle', label: 'Twitter Handle', type: 'string' },
  { key: 'websiteUrl', label: 'Website URL', type: 'string' },
  { key: 'companyName', label: 'Company Name', type: 'string' },
  { key: 'avatarUrl', label: 'Avatar URL', type: 'string' },
  { key: 'birthday', label: 'Birthday', type: 'date' },
  { key: 'industry', label: 'Industry', type: 'string' },
  { key: 'annualRevenueBand', label: 'Annual Revenue Band', type: 'string' },
  { key: 'employeeCountBand', label: 'Employee Count Band', type: 'string' },
  { key: 'metadata', label: 'Metadata (JSON)', type: 'json' },
];
