import type { CsvImportColumn } from '../csv-import.types';

export const ORG_ACCOUNTS_COLUMNS: CsvImportColumn[] = [
  {
    key: 'id',
    label: 'ID',
    type: 'string',
    description:
      'Provide an existing ID to update a record. Leave empty to create a new record.',
  },
  { key: 'name', label: 'Name', type: 'string' },
  { key: 'phone', label: 'Phone', type: 'string' },
  { key: 'phoneE164', label: 'Phone (E164)', type: 'string' },
  { key: 'email', label: 'Email', type: 'string' },
  { key: 'emailNormalized', label: 'Email (Normalized)', type: 'string' },
  { key: 'tags', label: 'Tags', type: 'string[]' },
  { key: 'categories', label: 'Categories', type: 'string[]' },
  { key: 'notes', label: 'Notes', type: 'string' },
  { key: 'lastActivityAt', label: 'Last Activity At', type: 'date' },
  { key: 'nextActivityAt', label: 'Next Activity At', type: 'date' },
  { key: 'score', label: 'Score', type: 'number' },
  { key: 'linkedinUrl', label: 'LinkedIn URL', type: 'string' },
  { key: 'twitterHandle', label: 'Twitter Handle', type: 'string' },
  { key: 'websiteUrl', label: 'Website URL', type: 'string' },
  { key: 'companyName', label: 'Company Name', type: 'string' },
  { key: 'avatarUrl', label: 'Avatar URL', type: 'string' },
  { key: 'birthday', label: 'Birthday', type: 'date' },
  { key: 'industry', label: 'Industry', type: 'string' },
  { key: 'annualRevenueBand', label: 'Annual Revenue Band', type: 'string' },
  { key: 'employeeCountBand', label: 'Employee Count Band', type: 'string' },
  {
    key: 'shippingAddressLine1',
    label: 'Shipping Address Line 1',
    type: 'string',
  },
  {
    key: 'shippingAddressLine2',
    label: 'Shipping Address Line 2',
    type: 'string',
  },
  { key: 'shippingCity', label: 'Shipping City', type: 'string' },
  { key: 'shippingRegion', label: 'Shipping Region', type: 'string' },
  { key: 'shippingPostalCode', label: 'Shipping Postal Code', type: 'string' },
  {
    key: 'shippingCountryCode',
    label: 'Shipping Country Code',
    type: 'string',
  },
  { key: 'shippingLatitude', label: 'Shipping Latitude', type: 'number' },
  { key: 'shippingLongitude', label: 'Shipping Longitude', type: 'number' },
  {
    key: 'billingAddressLine1',
    label: 'Billing Address Line 1',
    type: 'string',
  },
  {
    key: 'billingAddressLine2',
    label: 'Billing Address Line 2',
    type: 'string',
  },
  { key: 'billingCity', label: 'Billing City', type: 'string' },
  { key: 'billingRegion', label: 'Billing Region', type: 'string' },
  { key: 'billingPostalCode', label: 'Billing Postal Code', type: 'string' },
  { key: 'billingCountryCode', label: 'Billing Country Code', type: 'string' },
  { key: 'billingLatitude', label: 'Billing Latitude', type: 'number' },
  { key: 'billingLongitude', label: 'Billing Longitude', type: 'number' },
];
